project:
  type: book

book:
  title: "Teaching Reproducible Research Using R"
  author: "Christian Martinez"
  chapters:
    - index.qmd
    - chapters/course-blueprint.qmd
    - chapters/assignment-1.qmd
    - chapters/assignment-2.qmd
    - chapters/assignment-3.qmd
    - chapters/assignment-4.qmd
    - chapters/assignment-5.qmd
    - chapters/assignment-6.qmd
    - chapters/assignment-midterm.qmd
    - chapters/assignment-7.qmd
    - chapters/assignment-8.qmd
    - chapters/assignment-9.qmd
    - chapters/assignment-10.qmd
    - chapters/assignment-final.qmd
    - chapters/assignment-book.qmd

bibliography: bibliography/packages.bib
link-citations: true

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
    code-copy: true
    code-summary: "Show the code"
    toc: true
    number-sections: true

editor: visual

